name: PythonCI

# Especifica quando rodar o workflow (a cada push ou pull request na branch main) 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Define o job do CI.
jobs:
  build:
    runs-on: ubuntu-latest

    # Define os passos do CI
    steps:
      # Passo 1: Faz o checkout do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      # Passo 2: Configura a versão do Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Passo 3: Instala as dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Passo 4: Roda os testes (ou compila o código se houver algum processo de build)
      #- name: Run tests
      #  run: |
      #    python -m unittest discover

  test:
      needs: build
      name: CI (Test & Validations)
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'

        - name: Install dependencies of tests 
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        - name: Run tests pytest with coverage..
          run: |
            pip install pytest pytest-cov
            pytest --cov=todo_project --cov-report=xml

      # Passo 4: Roda os testes (ou compila o código se houver algum processo de build)
      - name: Run tests unittest
          run: |
          python -m unittest discover

        #- name: Upload coverage to Codecov
        #  uses: codecov/codecov-action@v2
        #  with:
        #    token: ${{ secrets.CODECOV_TOKEN }}
        #    file: ./coverage.xml
        #    fail_ci_if_error: true
        #  continue-on-error: true  

