name: PythonCI

# Especifica quando rodar o workflow (a cada push ou pull request na branch main) 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Define o job do CI.
jobs:
  build:
    runs-on: ubuntu-latest

    # Define os passos do CI
    steps:
      # Passo 1: Faz o checkout do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configura a versão do Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Passo 3: Instala as dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Passo 4: Roda os testes (ou compila o código se houver algum processo de build)
      #- name: Run tests
       # run: |
        ####  python -m unittest discover


